site_name: 'UrbanCode Velocity'
site_description: 'UrbanCode documentation.'
site_author: 'UrbanCode'

site_url: http://urbancode.hcldoc.com/velocity/11X/


theme:
  name: null

  # Set WINDMILL_DIR Environment Variable to use the below script.
  # Otherwise, specify the full path
  # custom_dir: <path-to-urbancode-windmill-theme>
  custom_dir: !!python/object/apply:os.getenv ["WINDMILL_DIR"]

  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

nav:
- Welcome: ucv_version_welcome.md
- Overview: #
  - Overview of UrbanCode Velocity: com.uvelocity.doc/topics/c_overview_se.md
  - Introduction to releases and pipelines: com.uvelocity.doc/topics/c_overview_release.md
  - Home page: com.uvelocity.doc/topics/c_overview_se_homepage.md
  - Key terminology: com.uvelocity.doc/topics/c_overview_terms.md
  - UrbanCode Velocity for GDPR Readiness: com.uvelocity.doc/topics/UCDVelocityGDPRguidelines.md
- Installation roadmap:
  - Overview: com.uvelocity.doc/topics/c_install_se_roadmap.md
  - Installing onto Docker Compose: com.uvelocity.doc/topics/t_install_se_docker.md
  - Installing on Kubernetes: com.uvelocity.doc/topics/t_install_minikube.md
  - Installing on IBM Cloud Private: com.uvelocity.doc/topics/t_install_ICP.md
  - Installing onto OpenShift: com.uvelocity.doc/topics/t_install_se_openShift.md
  - Uninstalling the server: com.uvelocity.doc/topics/t_install_se_remove_ucv.md
- Administration:
  - Overview: com.uvelocity.doc/topics/c_node_admin.md
  - Configuring an email server: com.uvelocity.doc/topics/t_admin_emailServer.md
  - Calendar settings: com.uvelocity.doc/topics/t_admin_calendar.md
  - Security:
    - Overview: com.uvelocity.doc/topics/c_node_security.md
    - Roles and permissions: com.uvelocity.doc/topics/c_admin_roles.md
    - Managing users: com.uvelocity.doc/topics/t_admin_authentication.md
    - Managing user groups: com.uvelocity.doc/topics/cr_security_groups.md
    - Managing teams: com.uvelocity.doc/topics/cr_security_teams.md
    - Managing user permissions: com.uvelocity.doc/topics/cr_security_permissions.md
    - Managing UrbanCode Deploy teams: com.uvelocity.doc/topics/cr_security_UCDteams.md
    - Changing the Administrator password: com.uvelocity.doc/topics/t_admin_password.md
  - Managing licenses: com.uvelocity.doc/topics/licenseManageHCL.md
  - Managing integrations:
    - Overview: com.uvelocity.doc/topics/c_node_integrations.md
    - Managing UrbanCode Deploy integrations: com.uvelocity.doc/topics/t_integration_UCD.md
    - Managing Jenkins integrations: com.uvelocity.doc/topics/t_integration_Jenkins.md
    - Integrating deployment risk analysis: com.uvelocity.doc/topics/c_integration_dra.md
    - Integrating with JIRA: com.uvelocity.doc/topics/c_integration_jira.md
    - Integrating with ServiceNow: com.uvelocity.doc/topics/c_integration_servicenow.md
    - Integrating quality and test data:
      - Overview: com.uvelocity.doc/topics/c_node_qualityData.md
      - Integrating code coverage data: com.uvelocity.doc/topics/quality-code-cover.md
      - Accessing JUnit data: com.uvelocity.doc/topics/quality-junit-data.md
      - Integrating SonarQube data: com.uvelocity.doc/topics/quality-sonarqube.md
      - Accessing Visual Studio quality data: com.uvelocity.doc/topics/quality-vStudio.md
- Release management:
  - Overview: com.crelease.doc/topics/c_node_releases.md
  - Managing a release: com.crelease.doc/topics/cr_release_managedetails.md
  - Managing releases: com.crelease.doc/topics/cr_release_manage.md
  - Creating releases: com.crelease.doc/topics/cr_release_create.md
  - Archiving releases: com.crelease.doc/topics/cr_release_archive.md
  - Events and tags: com.crelease.doc/topics/cr_events_ov.md
  - Restoring archived releases, plans, and templates: com.crelease.doc/topics/cr_restore_archive.md
  - Deployment plans:
    - Overview: com.crelease.doc/topics/cr_deployPlan_ov.md
    - Managing deployment plans: com.crelease.doc/topics/cr_deployplan_manage.md
    - Creating deployment plans: com.crelease.doc/topics/cr_deployPlan_create.md
    - Importing tasks into deployment plans: com.crelease.doc/topics/cr_deployPlan_importTasks.md
    - Copying deployment plans: com.crelease.doc/topics/cr_deployPlan_promote.md
    - Managing deployment plan templates: com.crelease.doc/topics/cr_deployPlan_template.md
    - Archiving deployment plans: com.crelease.doc/topics/cr_deployPlan_archive.md
  - Running deployments:
    - Overview: com.crelease.doc/topics/cr_deployRun_ov.md
    - Starting deployments manually: com.crelease.doc/topics/cr_deployRun_manual.md
    - Resolving tasks: com.crelease.doc/topics/cr_deployRun_taskResolve.md
    - Importing tasks into deployment plans: com.crelease.doc/topics/cr_deployPlan_importTasks.md
    - Running scheduled deployments: com.crelease.doc/topics/cr_deployRun_scheduled.md
  - Tasks:
    - Overview: com.crelease.doc/topics/cr_task_ov.md
    - Managing tasks: com.crelease.doc/topics/cr_task_manage.md
    - Creating tasks: com.crelease.doc/topics/cr_task_create.md
    - Managing task dependencies: com.crelease.doc/topics/cr_task_depend.md
    - Creating task groups: com.crelease.doc/topics/cr_task_groups.md
    - Managing task groups: com.crelease.doc/topics/cr_task_groups_manage.md
    - Managing task tags: com.crelease.doc/topics/cr_task_tags.md
    - Creating run another plan tasks: com.crelease.doc/topics/cr_taskType_another.md
    - Creating delay tasks: com.crelease.doc/topics/cr_taskType_delay.md
    - Deployment risk analysis tasks: com.crelease.doc/topics/cr_taskType_DRA.md
    - Creating email tasks: com.crelease.doc/topics/cr_taskType_email.md
    - Creating header/note tasks: com.crelease.doc/topics/cr_taskType_header.md
    - Creating Jenkins tasks: com.crelease.doc/topics/cr_taskType_Jenkins.md
    - Creating manual tasks: com.crelease.doc/topics/cr_taskType_manual.md
    - Creating ServiceNow tasks: com.crelease.doc/topics/cr_taskType_serviceNow.md
    - Creating UrbanCode Deploy tasks: com.crelease.doc/topics/cr_taskType_UCD.md
    - Creating wait for approval tasks: com.crelease.doc/topics/cr_taskType_waitForApproval.md
  - Properties:
    - Overview: com.crelease.doc/topics/cr_properties_ov.md
    - Creating properties: com.crelease.doc/topics/cr_properties_create.md
    - Using properties: com.crelease.doc/topics/cr_properties_ref.md
- Pipelines:
  - Overview: com.crelease.doc/topics/cr_pipelines_ov.md
  - Creating pipelines: com.crelease.doc/topics/cr_pipeline_create.md
  - Managing pipelines: com.crelease.doc/topics/cr_pipeline_manage.md
  - Running deployments with pipelines: com.crelease.doc/topics/cr_pipeline_run.md
- Reports:
  - Overview: com.uvelocity.doc/topics/c_node_reports.md
  - Custom reports:
    - Overview: com.insights.doc/topics/c_reports_custom.md
    - Cards: com.insights.doc/topics/c_reports_card.md
    - Charts: com.insights.doc/topics/c_reports_charts.md
  - Delivery Transformation reports:
    - Overview: com.insights.doc/topics/c_reports_efficiency.md
    - Events: com.insights.doc/topics/c_reports_events.md
- How to:
  - Overview: com.uvelocity.doc/topics/c_node_howto.md
  - Accessing the user interface: com.insights.doc/topics/t_ui_access.md
  - Create a report: com.insights.doc/topics/t_report_create.md
  - Filtering report data: com.insights.doc/topics/t_filter_data.md
  - Formatting Custom reports: com.insights.doc/topics/t_reports_format.md
  - Managing reports: com.insights.doc/topics/t_report_manage.md
  - Sharing reports: com.insights.doc/topics/t_reports_share.md
- Troubleshooting:
  - Overview: com.uvelocity.doc/topics/c_node_troubleshoot.md
  - Contacting support: com.insights.doc/topics/c_troubleshoot_contactsupport.md
  - Viewing log files: com.insights.doc/topics/t_troubleshoot_logfiles.md
  - Types of problems and checks to perform: com.insights.doc/topics/c_troubleshoot_problemtypes.md

markdown_extensions:
  - toc:
      permalink: '#'

extra:
  history_buttons: false
  version: !!python/object/apply:os.getenv ["DOC_VERSION"]
  article_nav_top: false
  article_nav_bottom: false
  logo: img\UClogo.png
